In [143]:
#1.DATA CLEANING:

In [144]:
import pandas as pd
import numpy as np

In [145]:
df = pd.read_csv("sample_data.csv")

In [146]:
#column rename:
df=df.rename(columns={"Years Exp":"Years of Experience","Emp ID":"Employee ID","Salary (INR)":"Salary"})
df

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary,Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,NaN
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,NaN
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,NaN
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,NaN
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,NaN
89,EMP089,Rohini,29,SQL,4,650000,2021-08-20,Database,NaN
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,NaN

In [147]:
#  remove duplicates
df.drop_duplicates()
df

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary,Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,NaN
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,NaN
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,NaN
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,NaN
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,NaN
89,EMP089,Rohini,29,SQL,4,650000,2021-08-20,Database,NaN
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,NaN

In [148]:
# Handle null values (drop) 
df.dropna()

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary,Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good

In [149]:
# Handle null values (fill)
df.fillna({"Employee ID": 000,"Employee Name": "abcd","AGE": 20,"Remarks": "good"}, inplace=True)
df

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary,Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,good
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,good
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,good
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,good
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,good
89,EMP089,Rohini,29,SQL,4,650000,2021-08-20,Database,good
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,good

In [150]:
#Change data types 
print(df.dtypes)

Employee ID            object
 Employee Name         object
AGE                    object
Skill Set              object
Years of Experience    object
Salary                 object
Date Of Joining        object
Department             object
Remarks                object
dtype: object

In [151]:
print(df["AGE"].unique())

['25' '28' '31' '29' '27' 20 '35' '22' '45' '30' 'twenty six' '24' '26'
 '32' '150' '-5' '33' '34' '23']

In [152]:
print(df["AGE"].dtype)
print(df["AGE"].head(10))

object
0    25
1    28
2    31
3    29
4    27
5    20
6    35
7    22
8    45
9    30
Name: AGE, dtype: object

In [153]:
print(df["Years of Experience"].unique())

['2' '4' '5' '3' '10' '1' '18' '6' '7' '8' nan 'three' '0' '-2' '40' '9']

In [154]:
df["Years of Experience"] = df["Years of Experience"].replace("three", 3)
df["Years of Experience"] = pd.to_numeric(df["Years of Experience"],errors="coerce")
df["Years of Experience"] = df["Years of Experience"].fillna(df["Years of Experience"].median())
df["Years of Experience"] = df["Years of Experience"].astype(int)
df.head()

,Employee ID,Employee Name,AGE,Skill Set,Years of Experience,Salary,Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,good
2,EMP003,Kiran Kumar,31,python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,good
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good

In [155]:
print(df.dtypes)

Employee ID            object
 Employee Name         object
AGE                    object
Skill Set              object
Years of Experience     int64
Salary                 object
Date Of Joining        object
Department             object
Remarks                object
dtype: object

In [156]:
df.rename(columns={"AGE": "Age"}, inplace=True)

In [157]:
df.columns

Index(['Employee ID', ' Employee Name ', 'Age', 'Skill Set',
       'Years of Experience', 'Salary', 'Date Of Joining', 'Department',
       'Remarks'],
      dtype='object')

In [158]:
#Standardize names 

df.columns = df.columns.str.strip()
df["Employee Name"] = df["Employee Name"].str.title()
df["Employee Name"].head()

0     Rahul Sharma
1       Anita Devi
2     Kiran Kumar
3       Priya Nair
4            Arjun
Name: Employee Name, dtype: object

In [159]:
#Standardize skills 

df["Skill Set"] = df["Skill Set"].astype(str).str.title()
df["Skill Set"].head()

0          Python
1            Java
2          Python
3    Data Science
4             C++
Name: Skill Set, dtype: object

In [160]:
#Clean salary values 

print(df["Salary"].unique())

['450000' '600000' '720000' '650000' '520000' '780000' '950000' '300000'
 '1200000' '850000' '550000' '480000' '490000' '700000' '900000' '800000'
 '250000' '620000' '590000' '680000' '1000000' '610000' '750000' nan
 '5,50,000' '350000' '980000' '760000' '500000' '320000' '1100000'
 '280000' '650000 INR' '$500000' '4.8L' '920000' '510000' '690000'
 '580000' '640000' '380000' 'Nine Lakhs' '460000' '310000' '99999999']

In [161]:
df["Salary"] = df["Salary"].replace({"5,50,000": "550000","650000 INR": "650000","$500000": "500000",
    "4.8L": "480000","Nine Lakhs": "900000","99999999": "990000",0: "500000"})
df

,Employee ID,Employee Name,Age,Skill Set,Years of Experience,Salary,Date Of Joining,Department,Remarks
0,EMP001,Rahul Sharma,25,Python,2,450000,12-01-2023,IT,Good
1,EMP002,Anita Devi,28,Java,4,600000,2022/05/11,IT,good
2,EMP003,Kiran Kumar,31,Python,5,720000,15-Jan-2021,IT,Excellent
3,EMP004,Priya Nair,29,Data Science,3,650000,2021-07-20,Analytics,good
4,EMP005,Arjun,27,C++,2,520000,10/10/2022,Development,Good
...,...,...,...,...,...,...,...,...,...
86,EMP086,Koushik,28,Machine Learning,4,720000,2021-12-12,AI,good
87,EMP087,Aarthi,24,Python,1,350000,2024-01-10,IT,good
88,EMP088,Pradeep,33,Data Science,8,1100000,2016-04-14,Analytics,good
89,EMP089,Rohini,29,Sql,4,650000,2021-08-20,Database,good
90,EMP090,Vijay,28,C++,3,580000,2022-09-09,Development,good

In [162]:
#Parse dates 

print(df["Date Of Joining"].dtype)

object

In [163]:
print(df["Salary"].dtype)

object

In [164]:


df["Salary"]=pd.to_numeric(df["Salary"])

In [165]:
#Detect and remove outliers 
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)
IQR = Q3 - Q1
df = df[(df["Salary"] >= Q1 - 1.5 * IQR) & (df["Salary"] <= Q3 + 1.5 * IQR)]
df.shape
print("Rows after removing outliers:", df.shape[0])

Rows after removing outliers: 89

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89 entries, 0 to 90
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee ID          89 non-null     object
 1   Employee Name        87 non-null     object
 2   Age                  89 non-null     object
 3   Skill Set            89 non-null     object
 4   Years of Experience  89 non-null     int64
 5   Salary               89 non-null     float64
 6   Date Of Joining      88 non-null     object
 7   Department           89 non-null     object
 8   Remarks              89 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 7.0+ KB

In [167]:
df["Age"]=df["Age"].str.replace("twenty six","26")

df["Age"]=pd.to_numeric(df["Age"])

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_3336\1278359755.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=df["Age"].str.replace("twenty six","26")
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_3336\1278359755.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=pd.to_numeric(df["Age"])

In [170]:
df["Years of Experience"]=pd.to_numeric(df["Years of Experience"])

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_3336\1828935537.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Years of Experience"]=pd.to_numeric(df["Years of Experience"])

In [171]:
#Validate ages and experience 

df["Age"]=pd.to_numeric(df["Age"])
df = df[(df["Age"] >= 18) & (df["Years of Experience"] >= 0) & (df["Years of Experience"] <= df["Age"])]
print(df)

   Employee ID  Employee Name   Age         Skill Set  Years of Experience  \
0       EMP001   Rahul Sharma  25.0            Python                    2
1       EMP002     Anita Devi  28.0              Java                    4
2       EMP003   Kiran Kumar   31.0            Python                    5
3       EMP004     Priya Nair  29.0      Data Science                    3
4       EMP005          Arjun  27.0               C++                    2
..         ...            ...   ...               ...                  ...
86      EMP086        Koushik  28.0  Machine Learning                    4
87      EMP087         Aarthi  24.0            Python                    1
88      EMP088        Pradeep  33.0      Data Science                    8
89      EMP089         Rohini  29.0               Sql                    4
90      EMP090          Vijay  28.0               C++                    3

       Salary Date Of Joining   Department    Remarks
0    450000.0      12-01-2023           IT       Good
1    600000.0      2022/05/11           IT       good
2    720000.0     15-Jan-2021           IT  Excellent
3    650000.0      2021-07-20    Analytics       good
4    520000.0      10/10/2022  Development       Good
..        ...             ...          ...        ...
86   720000.0      2021-12-12           AI       good
87   350000.0      2024-01-10           IT       good
88  1100000.0      2016-04-14    Analytics       good
89   650000.0      2021-08-20     Database       good
90   580000.0      2022-09-09  Development       good

[84 rows x 9 columns]

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_3336\1679081956.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=pd.to_numeric(df["Age"])

In [172]:
#Encode categorical variables 
df = pd.get_dummies(df, columns=["Remarks"])
df.head()

,Employee ID,Employee Name,Age,Skill Set,Years of Experience,Salary,Date Of Joining,Department,Remarks_Excellent,Remarks_Good,Remarks_good
0,EMP001,Rahul Sharma,25.0,Python,2,450000.0,12-01-2023,IT,False,True,False
1,EMP002,Anita Devi,28.0,Java,4,600000.0,2022/05/11,IT,False,False,True
2,EMP003,Kiran Kumar,31.0,Python,5,720000.0,15-Jan-2021,IT,True,False,False
3,EMP004,Priya Nair,29.0,Data Science,3,650000.0,2021-07-20,Analytics,False,False,True
4,EMP005,Arjun,27.0,C++,2,520000.0,10/10/2022,Development,False,True,False

In [174]:
#Scale numerical columns 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[["Age", "Years of Experience", "Salary"]] = scaler.fit_transform(df[["Age", "Years of Experience", "Salary"]])
df.head()

,Employee ID,Employee Name,Age,Skill Set,Years of Experience,Salary,Date Of Joining,Department,Remarks_Excellent,Remarks_Good,Remarks_good
0,EMP001,Rahul Sharma,-0.355426,Python,-0.803260,-1.074359,12-01-2023,IT,False,True,False
1,EMP002,Anita Devi,-0.134817,Java,-0.040844,-0.320213,2022/05/11,IT,False,False,True
2,EMP003,Kiran Kumar,0.085793,Python,0.340365,0.283104,15-Jan-2021,IT,True,False,False
3,EMP004,Priya Nair,-0.061280,Data Science,-0.422052,-0.068831,2021-07-20,Analytics,False,False,True
4,EMP005,Arjun,-0.208353,C++,-0.803260,-0.722424,10/10/2022,Development,False,True,False

In [175]:
#Feature selection
df = df.drop(["Employee ID", "Date Of Joining"], axis=1, errors="ignore")
df.head()

,Employee Name,Age,Skill Set,Years of Experience,Salary,Department,Remarks_Excellent,Remarks_Good,Remarks_good
0,Rahul Sharma,-0.355426,Python,-0.803260,-1.074359,IT,False,True,False
1,Anita Devi,-0.134817,Java,-0.040844,-0.320213,IT,False,False,True
2,Kiran Kumar,0.085793,Python,0.340365,0.283104,IT,True,False,False
3,Priya Nair,-0.061280,Data Science,-0.422052,-0.068831,Analytics,False,False,True
4,Arjun,-0.208353,C++,-0.803260,-0.722424,Development,False,True,False